### ISSUE TITLE
초안 만들어보기

### ISSUE THREAD

**Issue by phg98** [phg98/coffeetime#2]
일단 한번 만들어보자.
# coffeetime
회사 카페에서 커피를 주문후에 커피가 나올 때가 되면 알람을 주는 웹/앱

# 구성
- 사용자는 '대기표 번호'를 입력
- '대기표 번호'와 '현재 번호'가 가까워지면 알람 발생
- '현재 번호' 계산은
  - 커피 현황판 웹으로 부터 이미지를 받아와서
  - 숫자를 인식

**Comment by ChooX3** [comment]
우선 웹 앱 중에 하나 선택이 필요해 보입니다

**Comment by phg98** [comment]
어서오시고~ ㅎㅎ 
아무래도 웹부터 하는게 좋을 것 같은데, 근데 또 앱을 하고 싶은 분이 있으면 그것도 나쁘지는 않고~
