### ISSUE TITLE
기존 웹 페이지 읽어서 영상 받기

### ISSUE THREAD

**Issue by phg98** [phg98/coffeetime#8]
# 기존 웹 페이지 읽어서 영상 받기
---
기존 카페 웹 페이지 내용 가져와서 영상 부분만 저장하여 반환하는 함수/모듈 만들기
_기존 카페 웹 주소는 언급하지 맙시다_

**Comment by phg98** [comment]
테스트 용으로 해보는중. #8 브랜치 참고.

**Comment by phg98** [comment]
AI의 도움으로 무지성으로 해보고 있는데
- CORS에러발생 -> api.allorigins.win 사용하여 임시 해결
- 웹페이지는 가져왔지만 이미지는 안보임 
  - 이미지를 base64변환해서 저장하도록 수정했는데 그래도 안됨 
  - html2canvas로 캡쳐하도록 했는데 그래도 안됨
  - 이후에도 여러번 수정해봤는데 아직 해결 안됨. 
  - **다른 분들 도움요청해보고 그래도 안되면 서버에서 puppeteer같은걸로 해야 할듯?**

**Comment by phg98** [comment]
ChatGPT o1이 새로 나왔다니까 유료결재해서 함 물어볼까 합니다. 
주말까지 그래도 안되면 서버로 전환해야 할듯...

**Comment by CamueXO** [comment]
blob ?.. CORS ? 이미지 파일 하나 받는게 이리 어렵네요.... ㅡㅡ;; ㅋ

**Comment by CamueXO** [comment]
일단 서버 넣어서 영상 받는건 성공!!!

**Comment by phg98** [comment]
그럼 커밋하고 Pull Request 보내시면 제가 올려보겠슴다

**Comment by phg98** [comment]
main에 반영하였고 다른 이슈들은 별도 이슈로 생성하고 이 건은 완료처리합니다.
